use_frameworks!

platform :ios, '13.0'

target 'LZPhotoBrowser_Example' do
  pod 'LZPhotoBrowser', :path => '../'

  target 'LZPhotoBrowser_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
